<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<script>


    new Promise((resolve, reject)=>{
        const rnd = 300 + Math.floor(Math.random()*1000);
        setTimeout(()=>{
            resolve('rnd');
        },rnd);
    }).then(r => {
        console.log('2:', r,);
        return  new Promise((resolve, reject)=>{
            const rnd = 300 + Math.floor(Math.random()*1000);
            setTimeout(()=>{
                resolve('rnd');
            },rnd);
        })//這個then處理完的結果會進到下一個then裡面執行
    }).then(r => {
        console.log('3:', r,);
    }).catch(err => {
        //reject會進到這裏  catch捕捉的到前面發生的錯誤
        console.log('error',err)
        })




</script>


</body>
</html>